### ISSUE TITLE
Olny part of stories in manual_alignments.zip

### ISSUE THREAD

**Issue by ziweiji** [achaudhury/shmoop-corpus#4]
File manual_alignments.zip just includes 15 stories. Where can I find the complete alignment for all 232 stories?

**Comment by makarandtapaswi** [comment]
Hi,
arXiv: https://arxiv.org/pdf/1912.13082.pdf
The manually aligned validation set contains 360 chapters (from 15 stories) with a total of 13.5k aligned summary paragraphs.
